<?php 
	   $ad_postion=Util::com_ad_position();
	   $regions=Region::model()->get_options_regions();
       $this->widget('AddItems', array( 
          'model'=>$model, 
          'name'=>'广告管理',
          //用户操作
          'user_operate'=>array(
              array(
               'name'=>'返回到广告管理',
               'value'=>$this->createUrl("index",array()),
             ),
             array(
				       'name'=>'新增广告',
				       'value'=>$this->createUrl("add",array())
				     ),
          ),
          //增加的内容字段
      'add_datas'=>array(
		    'region_id'=>array(
				'name'=>'区域',
				'type'=>'multi',
				'value'=>$regions,
				'htmlOptions'=>array(),
			 ),
      'type_id'=>array(
				'name'=>'广告位置',
				'type'=>'select',//搜索框的类型
				'value'=>$ad_postion,
				'htmlOptions'=>array(),
      ),     
      'title'=>array(
        'name'=>'标题',
        'type'=>'text',
        'value'=>'',
        'htmlOptions'=>array(),
       ),     
       'content'=>array(
        'name'=>'内容',
        'type'=>'multitext',
        'value'=>'',
        'htmlOptions'=>array(),
        ),
			),

			 //最下面操作按钮
			'operates'=>array(
				array(
				   
				),
			),
       ));
?>